---
name: ci

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*'

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'pkgbuild'
          pkgname: '.build_action'

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'srcinfo'
          pkgname: '.build_action'

      - name: Validate binary
        id: validate-ssserver
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'run'
          pkgname: '.build_action'
          command: 'ssserver-rust -V'

      - name: Validate binary
        id: validate-ssmanager
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'run'
          pkgname: '.build_action'
          command: 'ssmanager-rust -V'

      - name: Validate binary
        id: validate-sslocal
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: 'run'
          pkgname: '.build_action'
          command: 'sslocal-rust -V'

      - name: Upload Arch Linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: '.build_action/shadowsocks-rust-bin-*-*-x86_64.pkg.tar.zst'
          asset_name: 'shadowsocks-rust-bin-*-*-x86_64.pkg.tar.zst'
          asset_content_type: application/octet-stream
